# Generated by Django 3.2.3 on 2024-05-12 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240512_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='recipe_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
