# Generated by Django 3.2.3 on 2024-05-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20240512_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_link',
            field=models.CharField(max_length=20, verbose_name='Короткая ссылка на рецепт'),
        ),
    ]
