# Generated by Django 3.2.3 on 2024-05-12 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_link_short_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
